In [1]:
import pandas as pd
import numpy as np
import sqlite3

def main():
    db = sqlite3.connect('gvk/std_gpcr.db')
    tables = pd.read_sql_query("select name from sqlite_master where type = 'table';", db)
    display(tables)

    posi = pd.read_sql_query('select * from posi', db)
    
    print('Unordered positive pairs')
    display(posi[posi['id'] == 0])
    
    #print('Ordered positive pairs')
    #display(posi[posi['id'] == 1])

    nega = pd.read_sql_query('select * from nega', db)

    for i in nega['id'].unique():
        print('Negative pairs %d/5' % i)
        display(nega[nega['id'] == i])

    prot = pd.read_sql_query('select * from ptable', db)
    prot = prot.rename(columns={'name':'prot'})
    display(prot)

    chem = pd.read_sql_query('select * from ctable', db)
    chem = chem.rename(columns={'name':'chem'})
    display(chem)

    for i in nega['id'].unique():
        df = pd.concat([posi[posi['id'] == 0], nega[nega['id'] == i]])
        df = pd.merge(df, chem, on='chem')
        df = pd.merge(df, prot, on='prot')
        df = df.set_index(['id', 'chem', 'prot'])
        display(df)

if __name__ == '__main__':
    main()

          name
0         posi
1         nega
2      fptable
3        model
4      protein
5       ptable
6      comment
7       ctable
8     s_ctable
9     s_ptable
10  pca_ctable
11  pca_ptable

Unordered positive pairs

        id       chem         prot
0        0  C01389645  BKRB2_HUMAN
1        0  C00442190  P2RY1_HUMAN
2        0  C00112244    V2R_HUMAN
3        0  C00458620  PE2R2_HUMAN
4        0  C01484670  GPR34_HUMAN
...     ..        ...          ...
124865   0  C00333126  P2Y10_HUMAN
124866   0  C00275578   ACM2_HUMAN
124867   0  C00638889   DRD1_HUMAN
124868   0  C00573862   GHSR_HUMAN
124869   0  C00046238   GHSR_HUMAN

[124870 rows x 3 columns]

Negative pairs 1/5

        id       chem         prot
0        1  C00260217  ADA1B_HUMAN
1        1  C00094769  EDNRA_HUMAN
2        1  C00516710  PE2R2_HUMAN
3        1  C01321071   ACM2_HUMAN
4        1  C00482150    V2R_HUMAN
...     ..        ...          ...
123320   1  C00079088  NPSR1_HUMAN
123321   1  C00353392   OPRD_HUMAN
123322   1  C01834502  5HT4R_HUMAN
123323   1  C00368826  5HT2B_HUMAN
123324   1  C00526928  CXCR1_HUMAN

[123325 rows x 3 columns]

Negative pairs 2/5

        id       chem         prot
123325   2  C00187081   ACM2_HUMAN
123326   2  C00372123   DRD5_HUMAN
123327   2  C00206482   GRM7_HUMAN
123328   2  C00021253   CCR9_HUMAN
123329   2  C00000867  GPBAR_HUMAN
...     ..        ...          ...
246653   2  C00055630  5HT1F_HUMAN
246654   2  C00639911   PD2R_HUMAN
246655   2  C00213669   V1AR_HUMAN
246656   2  C00038261  CXCR3_HUMAN
246657   2  C00353385  MTR1B_HUMAN

[123333 rows x 3 columns]

Negative pairs 3/5

        id       chem         prot
246658   3  C00222084   CCR6_HUMAN
246659   3  C01488842    GLR_HUMAN
246660   3  C00219679  5HT1F_HUMAN
246661   3  C00405117   GRM7_HUMAN
246662   3  C00277175  ADA2C_HUMAN
...     ..        ...          ...
369959   3  C00322995  MCHR2_HUMAN
369960   3  C00039707  CALRL_HUMAN
369961   3  C00265000  EDNRA_HUMAN
369962   3  C00054405   ACM4_HUMAN
369963   3  C00127104   GRM1_HUMAN

[123306 rows x 3 columns]

Negative pairs 4/5

        id       chem         prot
369964   4  C00293699  LT4R2_HUMAN
369965   4  C01362872  5HT4R_HUMAN
369966   4  C00529555   GASR_HUMAN
369967   4  C01314210   FSHR_HUMAN
369968   4  C00080905   GRM8_HUMAN
...     ..        ...          ...
493317   4  C00560874   SSR1_HUMAN
493318   4  C00217927  NPY6R_HUMAN
493319   4  C01457330  GALR3_HUMAN
493320   4  C01329690  CXCR5_HUMAN
493321   4  C00673827  PE2R2_HUMAN

[123358 rows x 3 columns]

Negative pairs 5/5

        id       chem         prot
493322   5  C00457634   GRM7_HUMAN
493323   5  C00197715   TBB3_HUMAN
493324   5  C01482058  AGTR2_HUMAN
493325   5  C01762200   GRM2_HUMAN
493326   5  C01378650   DRD4_HUMAN
...     ..        ...          ...
616671   5  C01431716   NK2R_HUMAN
616672   5  C00356912  GPBAR_HUMAN
616673   5  C00417692  P2RY1_HUMAN
616674   5  C01710911  ADA1D_HUMAN
616675   5  C00264528  TAAR1_HUMAN

[123354 rows x 3 columns]

,prot,p0001,p0002,p0003,p0004,p0005,p0006,p0007,p0008,p0009,...,p1071,p1072,p1073,p1074,p1075,p1076,p1077,p1078,p1079,p1080
0,5HT1A_HUMAN,9.71564,3.31754,3.79147,3.55450,4.02844,7.10900,1.42180,6.87204,4.97630,...,-0.001710,-0.002152,-0.000922,0.001942,0.002892,0.001709,0.004074,202.556,154.619,153.216
1,5HT1B_HUMAN,8.97436,2.82051,3.58974,3.33333,4.35897,3.07692,1.28205,7.94872,4.61539,...,0.001385,-0.001081,0.001078,0.000261,0.000605,0.002897,0.005541,191.074,151.592,145.397
2,5HT1D_HUMAN,9.81432,2.91777,2.65252,3.18302,4.50928,3.71353,2.65252,10.87530,3.18302,...,-0.000851,0.000189,0.002530,0.000504,0.001763,0.001168,0.003632,183.963,144.543,145.794
3,5HT1E_HUMAN,6.57534,3.28767,3.56164,3.28767,4.65753,2.46575,2.73973,10.13700,4.38356,...,0.000594,-0.001859,-0.001225,-0.000144,-0.000322,0.004455,0.004296,182.469,142.853,141.496
4,5HT1F_HUMAN,6.28415,3.00546,4.09836,4.64481,4.37158,3.00546,2.73224,10.10930,6.28415,...,0.001460,-0.003396,-0.004019,-0.001459,-0.003692,0.002896,0.006617,177.790,141.275,133.312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,GP146_HUMAN,8.70871,2.70270,3.30330,2.40240,3.90390,6.30631,3.90390,2.10210,2.40240,...,0.002855,-0.002319,-0.000743,-0.002323,0.002050,0.001792,0.001462,160.926,122.408,136.160
803,GP148_HUMAN,9.51009,2.88184,2.01729,2.01729,2.88184,6.05187,3.17003,6.62824,1.15274,...,0.003764,0.000924,0.002788,0.001192,0.002528,0.003011,0.006033,163.333,133.623,151.277
804,GP149_HUMAN,5.74555,2.59918,4.24077,5.74555,3.96717,5.74555,1.91518,4.37756,4.37756,...,0.001939,0.003579,0.002188,0.003360,0.003154,0.001885,0.000967,375.235,236.392,241.883
805,GP150_HUMAN,14.74650,2.76498,2.07373,3.45622,3.22581,9.44701,2.53456,1.38249,1.15207,...,0.004510,-0.001176,-0.002706,0.000151,0.003864,0.002123,0.001600,204.506,163.615,167.043
806,GP151_HUMAN,8.59188,1.67064,3.57995,5.48926,5.25060,5.01193,2.62530,5.96659,5.72792,...,0.002297,0.000505,0.002264,0.000228,-0.001370,0.000020,0.001708,209.457,164.638,152.947

,chem,c0001,c0002,c0003,c0004,c0005,c0006,c0007,c0008,c0009,...,c0885,c0886,c0887,c0888,c0889,c0890,c0891,c0892,c0893,c0894
0,C00000001,267.35,7.226,23.665,36.825,25.006,41.239,0.640,0.995,0.676,...,343.938,88.491,85.367,336.993,141.489,244.16,0.980,-3.57,-3.76,-3.80
1,C00000002,213.68,8.218,16.439,26.382,17.341,29.352,0.632,1.015,0.667,...,295.955,100.725,75.581,261.894,110.711,191.53,0.885,-3.18,-3.32,-3.34
2,C00000004,376.64,5.621,36.680,65.654,40.591,75.932,0.547,0.980,0.606,...,650.202,128.050,128.050,551.512,229.406,406.59,0.848,-4.90,-5.24,-5.36
3,C00000006,248.36,6.536,22.214,37.811,23.773,43.152,0.585,0.995,0.626,...,369.850,71.694,77.480,333.721,140.148,233.26,0.902,-2.50,-2.56,-2.54
4,C00000009,196.70,7.565,16.031,25.829,17.438,29.432,0.617,0.993,0.671,...,254.122,21.135,18.011,248.073,105.046,175.23,0.976,-3.17,-3.31,-3.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84959,C02005161,298.36,8.064,25.918,36.833,27.034,40.697,0.700,0.995,0.731,...,363.669,46.116,0.000,378.322,158.427,263.27,1.040,-5.92,-6.38,-6.55
84960,C02005165,348.42,8.103,30.445,42.716,31.796,47.112,0.708,0.993,0.739,...,410.107,43.078,0.000,439.618,183.548,303.93,1.072,-5.61,-6.03,-6.19
84961,C02005329,427.52,8.907,33.885,48.542,35.154,53.322,0.706,1.011,0.732,...,463.188,104.190,0.000,491.960,205.000,337.21,1.062,-5.59,-6.02,-6.17
84962,C02005438,269.36,8.979,20.875,30.236,21.960,33.657,0.696,1.008,0.732,...,286.604,68.245,34.674,310.199,130.508,206.35,1.082,-3.59,-3.78,-3.82
84963,C02005568,294.37,7.956,26.204,36.505,27.580,40.488,0.708,0.987,0.745,...,329.880,16.786,16.786,373.937,156.630,248.52,1.134,-4.62,-4.93,-5.03

                           c0001   c0002   c0003   c0004   c0005    c0006  \
id chem      prot
0  C01389645 BKRB2_HUMAN  598.05   5.921  56.431  98.777  62.893  114.459
   C00281394 BKRB2_HUMAN  488.50   7.633  40.051  63.861  43.063   72.030
1  C00245994 BKRB2_HUMAN  513.76   7.136  45.110  71.174  48.756   80.477
0  C00072985 BKRB2_HUMAN  402.32  10.316  28.782  39.658  30.404   43.004
1  C00001083 BKRB2_HUMAN  265.39   6.805  24.279  38.374  26.108   43.817
...                          ...     ...     ...     ...     ...      ...
   C00609002 GPR18_HUMAN  465.37   8.781  34.868  54.200  36.171   59.871
   C00203597 TA2R1_HUMAN  454.62   8.578  35.345  53.494  37.534   59.198
0  C00644907 TA2R1_HUMAN  362.51   6.473  32.476  55.891  34.694   63.275
1  C00426398 OPN4_HUMAN   451.68   6.453  40.965  69.301  44.120   79.554
0  C00023748 OPN4_HUMAN   292.42   6.092  25.664  48.334  27.387   55.069

                          c0007  c0008  c0009  c0010  ...     p1071     p1072  \
id chem      prot                                     ...
0  C01389645 BKRB2_HUMAN  0.559  0.978  0.623  1.133  ...  0.000559  0.000420
   C00281394 BKRB2_HUMAN  0.626  0.998  0.673  1.125  ...  0.000559  0.000420
1  C00245994 BKRB2_HUMAN  0.627  0.989  0.677  1.118  ...  0.000559  0.000420
0  C00072985 BKRB2_HUMAN  0.738  1.017  0.780  1.103  ...  0.000559  0.000420
1  C00001083 BKRB2_HUMAN  0.623  0.984  0.669  1.124  ...  0.000559  0.000420
...                         ...    ...    ...    ...  ...       ...       ...
   C00609002 GPR18_HUMAN  0.658  1.023  0.682  1.130  ... -0.001749  0.000249
   C00203597 TA2R1_HUMAN  0.667  1.009  0.708  1.117  ...  0.001455 -0.002031
0  C00644907 TA2R1_HUMAN  0.580  0.998  0.620  1.130  ...  0.001455 -0.002031
1  C00426398 OPN4_HUMAN   0.585  0.990  0.630  1.136  ...  0.003867  0.002336
0  C00023748 OPN4_HUMAN   0.535  1.007  0.571  1.147  ...  0.003867  0.002336

                             p1073     p1074     p1075     p1076     p1077  \
id chem      prot
0  C01389645 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00281394 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
1  C00245994 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
0  C00072985 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
1  C00001083 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
...                            ...       ...       ...       ...       ...
   C00609002 GPR18_HUMAN  0.001586 -0.000971  0.000254  0.002740  0.005966
   C00203597 TA2R1_HUMAN  0.000426  0.002173  0.002895  0.000126  0.004464
0  C00644907 TA2R1_HUMAN  0.000426  0.002173  0.002895  0.000126  0.004464
1  C00426398 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874
0  C00023748 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874

                            p1078    p1079    p1080
id chem      prot
0  C01389645 BKRB2_HUMAN  190.160  149.947  156.745
   C00281394 BKRB2_HUMAN  190.160  149.947  156.745
1  C00245994 BKRB2_HUMAN  190.160  149.947  156.745
0  C00072985 BKRB2_HUMAN  190.160  149.947  156.745
1  C00001083 BKRB2_HUMAN  190.160  149.947  156.745
...                           ...      ...      ...
   C00609002 GPR18_HUMAN  165.222  139.460  136.582
   C00203597 TA2R1_HUMAN  137.815  135.804  136.567
0  C00644907 TA2R1_HUMAN  137.815  135.804  136.567
1  C00426398 OPN4_HUMAN   235.420  180.596  181.610
0  C00023748 OPN4_HUMAN   235.420  180.596  181.610

[248195 rows x 1974 columns]

                           c0001   c0002   c0003   c0004   c0005    c0006  \
id chem      prot
0  C01389645 BKRB2_HUMAN  598.05   5.921  56.431  98.777  62.893  114.459
   C00281394 BKRB2_HUMAN  488.50   7.633  40.051  63.861  43.063   72.030
   C00072985 BKRB2_HUMAN  402.32  10.316  28.782  39.658  30.404   43.004
2  C00000857 BKRB2_HUMAN  373.99   7.632  30.874  48.425  33.898   54.926
   C00001102 BKRB2_HUMAN  370.63   7.267  31.739  49.960  35.444   56.819
...                          ...     ...     ...     ...     ...      ...
0  C00021215 SUCR1_HUMAN  118.10   8.436   8.440  14.960   8.102   16.083
2  C00208718 CML1_HUMAN   444.41   8.385  34.546  53.312  36.608   60.113
0  C01718162 CML1_HUMAN   406.62   6.069  37.583  66.425  40.739   75.936
2  C00609667 OPN4_HUMAN   570.79   7.510  48.514  75.789  51.699   85.315
0  C00023748 OPN4_HUMAN   292.42   6.092  25.664  48.334  27.387   55.069

                          c0007  c0008  c0009  c0010  ...     p1071     p1072  \
id chem      prot                                     ...
0  C01389645 BKRB2_HUMAN  0.559  0.978  0.623  1.133  ...  0.000559  0.000420
   C00281394 BKRB2_HUMAN  0.626  0.998  0.673  1.125  ...  0.000559  0.000420
   C00072985 BKRB2_HUMAN  0.738  1.017  0.780  1.103  ...  0.000559  0.000420
2  C00000857 BKRB2_HUMAN  0.630  0.988  0.692  1.121  ...  0.000559  0.000420
   C00001102 BKRB2_HUMAN  0.622  0.980  0.695  1.114  ...  0.000559  0.000420
...                         ...    ...    ...    ...  ...       ...       ...
0  C00021215 SUCR1_HUMAN  0.603  1.069  0.579  1.149  ...  0.001155  0.002504
2  C00208718 CML1_HUMAN   0.652  1.006  0.691  1.134  ...  0.004885  0.004065
0  C01718162 CML1_HUMAN   0.561  0.991  0.608  1.133  ...  0.004885  0.004065
2  C00609667 OPN4_HUMAN   0.638  0.997  0.680  1.123  ...  0.003867  0.002336
0  C00023748 OPN4_HUMAN   0.535  1.007  0.571  1.147  ...  0.003867  0.002336

                             p1073     p1074     p1075     p1076     p1077  \
id chem      prot
0  C01389645 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00281394 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00072985 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
2  C00000857 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00001102 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
...                            ...       ...       ...       ...       ...
0  C00021215 SUCR1_HUMAN  0.003405  0.002044  0.004069  0.001612  0.003456
2  C00208718 CML1_HUMAN   0.004887  0.001522  0.003042  0.003457  0.006119
0  C01718162 CML1_HUMAN   0.004887  0.001522  0.003042  0.003457  0.006119
2  C00609667 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874
0  C00023748 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874

                            p1078    p1079    p1080
id chem      prot
0  C01389645 BKRB2_HUMAN  190.160  149.947  156.745
   C00281394 BKRB2_HUMAN  190.160  149.947  156.745
   C00072985 BKRB2_HUMAN  190.160  149.947  156.745
2  C00000857 BKRB2_HUMAN  190.160  149.947  156.745
   C00001102 BKRB2_HUMAN  190.160  149.947  156.745
...                           ...      ...      ...
0  C00021215 SUCR1_HUMAN  168.568  140.875  138.337
2  C00208718 CML1_HUMAN   191.358  146.038  149.270
0  C01718162 CML1_HUMAN   191.358  146.038  149.270
2  C00609667 OPN4_HUMAN   235.420  180.596  181.610
0  C00023748 OPN4_HUMAN   235.420  180.596  181.610

[248203 rows x 1974 columns]

                           c0001   c0002   c0003   c0004   c0005    c0006  \
id chem      prot
0  C01389645 BKRB2_HUMAN  598.05   5.921  56.431  98.777  62.893  114.459
   C00281394 BKRB2_HUMAN  488.50   7.633  40.051  63.861  43.063   72.030
3  C00353363 BKRB2_HUMAN  476.52   8.216  37.370  59.716  37.819   66.753
0  C00072985 BKRB2_HUMAN  402.32  10.316  28.782  39.658  30.404   43.004
3  C00353402 BKRB2_HUMAN  448.59   7.120  37.852  63.527  39.711   72.450
...                          ...     ...     ...     ...     ...      ...
   C00101421 LPAR5_HUMAN  579.75   7.628  46.743  77.134  49.000   86.745
   C00343410 LPAR5_HUMAN  408.61   7.169  35.508  56.421  38.466   63.733
0  C00061163 LPAR5_HUMAN  436.59   6.237  37.990  69.821  41.853   79.909
   C00644907 TA2R1_HUMAN  362.51   6.473  32.476  55.891  34.694   63.275
3  C00494128 TA2R1_HUMAN  467.72   6.236  43.218  74.076  46.847   85.012

                          c0007  c0008  c0009  c0010  ...     p1071     p1072  \
id chem      prot                                     ...
0  C01389645 BKRB2_HUMAN  0.559  0.978  0.623  1.133  ...  0.000559  0.000420
   C00281394 BKRB2_HUMAN  0.626  0.998  0.673  1.125  ...  0.000559  0.000420
3  C00353363 BKRB2_HUMAN  0.644  1.030  0.652  1.151  ...  0.000559  0.000420
0  C00072985 BKRB2_HUMAN  0.738  1.017  0.780  1.103  ...  0.000559  0.000420
3  C00353402 BKRB2_HUMAN  0.601  1.008  0.630  1.150  ...  0.000559  0.000420
...                         ...    ...    ...    ...  ...       ...       ...
   C00101421 LPAR5_HUMAN  0.615  1.015  0.645  1.141  ... -0.000740 -0.000270
   C00343410 LPAR5_HUMAN  0.623  0.990  0.675  1.118  ... -0.000740 -0.000270
0  C00061163 LPAR5_HUMAN  0.543  0.997  0.598  1.142  ... -0.000740 -0.000270
   C00644907 TA2R1_HUMAN  0.580  0.998  0.620  1.130  ...  0.001455 -0.002031
3  C00494128 TA2R1_HUMAN  0.576  0.988  0.625  1.133  ...  0.001455 -0.002031

                             p1073     p1074     p1075     p1076     p1077  \
id chem      prot
0  C01389645 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00281394 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
3  C00353363 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
0  C00072985 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
3  C00353402 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
...                            ...       ...       ...       ...       ...
   C00101421 LPAR5_HUMAN -0.002045 -0.000786  0.000671  0.001416  0.001838
   C00343410 LPAR5_HUMAN -0.002045 -0.000786  0.000671  0.001416  0.001838
0  C00061163 LPAR5_HUMAN -0.002045 -0.000786  0.000671  0.001416  0.001838
   C00644907 TA2R1_HUMAN  0.000426  0.002173  0.002895  0.000126  0.004464
3  C00494128 TA2R1_HUMAN  0.000426  0.002173  0.002895  0.000126  0.004464

                            p1078    p1079    p1080
id chem      prot
0  C01389645 BKRB2_HUMAN  190.160  149.947  156.745
   C00281394 BKRB2_HUMAN  190.160  149.947  156.745
3  C00353363 BKRB2_HUMAN  190.160  149.947  156.745
0  C00072985 BKRB2_HUMAN  190.160  149.947  156.745
3  C00353402 BKRB2_HUMAN  190.160  149.947  156.745
...                           ...      ...      ...
   C00101421 LPAR5_HUMAN  183.728  135.158  152.730
   C00343410 LPAR5_HUMAN  183.728  135.158  152.730
0  C00061163 LPAR5_HUMAN  183.728  135.158  152.730
   C00644907 TA2R1_HUMAN  137.815  135.804  136.567
3  C00494128 TA2R1_HUMAN  137.815  135.804  136.567

[248176 rows x 1974 columns]

                           c0001   c0002   c0003   c0004   c0005    c0006  \
id chem      prot
0  C01389645 BKRB2_HUMAN  598.05   5.921  56.431  98.777  62.893  114.459
   C00281394 BKRB2_HUMAN  488.50   7.633  40.051  63.861  43.063   72.030
   C00072985 BKRB2_HUMAN  402.32  10.316  28.782  39.658  30.404   43.004
4  C00353402 BKRB2_HUMAN  448.59   7.120  37.852  63.527  39.711   72.450
   C00030337 BKRB2_HUMAN  137.20   6.533  12.370  20.847  13.267   23.784
...                          ...     ...     ...     ...     ...      ...
   C00233151 TA2R1_HUMAN  461.50   8.546  38.138  54.683  38.926   59.654
0  C00021215 SUCR1_HUMAN  118.10   8.436   8.440  14.960   8.102   16.083
4  C00666422 SUCR1_HUMAN  402.45   8.049  32.417  51.116  33.108   57.002
   C00620625 OPN4_HUMAN   593.77   7.422  52.637  79.425  55.563   88.766
0  C00023748 OPN4_HUMAN   292.42   6.092  25.664  48.334  27.387   55.069

                          c0007  c0008  c0009  c0010  ...     p1071     p1072  \
id chem      prot                                     ...
0  C01389645 BKRB2_HUMAN  0.559  0.978  0.623  1.133  ...  0.000559  0.000420
   C00281394 BKRB2_HUMAN  0.626  0.998  0.673  1.125  ...  0.000559  0.000420
   C00072985 BKRB2_HUMAN  0.738  1.017  0.780  1.103  ...  0.000559  0.000420
4  C00353402 BKRB2_HUMAN  0.601  1.008  0.630  1.150  ...  0.000559  0.000420
   C00030337 BKRB2_HUMAN  0.589  0.993  0.632  1.133  ...  0.000559  0.000420
...                         ...    ...    ...    ...  ...       ...       ...
   C00233151 TA2R1_HUMAN  0.706  1.013  0.721  1.105  ...  0.001455 -0.002031
0  C00021215 SUCR1_HUMAN  0.603  1.069  0.579  1.149  ...  0.001155  0.002504
4  C00666422 SUCR1_HUMAN  0.648  1.022  0.662  1.140  ...  0.001155  0.002504
   C00620625 OPN4_HUMAN   0.658  0.993  0.695  1.110  ...  0.003867  0.002336
0  C00023748 OPN4_HUMAN   0.535  1.007  0.571  1.147  ...  0.003867  0.002336

                             p1073     p1074     p1075     p1076     p1077  \
id chem      prot
0  C01389645 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00281394 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00072985 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
4  C00353402 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00030337 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
...                            ...       ...       ...       ...       ...
   C00233151 TA2R1_HUMAN  0.000426  0.002173  0.002895  0.000126  0.004464
0  C00021215 SUCR1_HUMAN  0.003405  0.002044  0.004069  0.001612  0.003456
4  C00666422 SUCR1_HUMAN  0.003405  0.002044  0.004069  0.001612  0.003456
   C00620625 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874
0  C00023748 OPN4_HUMAN   0.002256  0.001587  0.002783  0.003458  0.005874

                            p1078    p1079    p1080
id chem      prot
0  C01389645 BKRB2_HUMAN  190.160  149.947  156.745
   C00281394 BKRB2_HUMAN  190.160  149.947  156.745
   C00072985 BKRB2_HUMAN  190.160  149.947  156.745
4  C00353402 BKRB2_HUMAN  190.160  149.947  156.745
   C00030337 BKRB2_HUMAN  190.160  149.947  156.745
...                           ...      ...      ...
   C00233151 TA2R1_HUMAN  137.815  135.804  136.567
0  C00021215 SUCR1_HUMAN  168.568  140.875  138.337
4  C00666422 SUCR1_HUMAN  168.568  140.875  138.337
   C00620625 OPN4_HUMAN   235.420  180.596  181.610
0  C00023748 OPN4_HUMAN   235.420  180.596  181.610

[248228 rows x 1974 columns]

                           c0001   c0002   c0003   c0004   c0005    c0006  \
id chem      prot
0  C01389645 BKRB2_HUMAN  598.05   5.921  56.431  98.777  62.893  114.459
   C00281394 BKRB2_HUMAN  488.50   7.633  40.051  63.861  43.063   72.030
5  C00995841 BKRB2_HUMAN  217.32   7.494  17.041  29.345  18.347   32.953
0  C00072985 BKRB2_HUMAN  402.32  10.316  28.782  39.658  30.404   43.004
5  C00353368 BKRB2_HUMAN  426.58   6.993  36.594  61.196  38.534   69.600
...                          ...     ...     ...     ...     ...      ...
   C00104971 NMUR2_HUMAN  284.44   6.321  26.552  44.251  28.841   50.773
0  C01718162 CML1_HUMAN   406.62   6.069  37.583  66.425  40.739   75.936
5  C00348566 CML1_HUMAN   417.52   8.521  33.610  49.433  35.120   54.365
0  C00021215 SUCR1_HUMAN  118.10   8.436   8.440  14.960   8.102   16.083
5  C00453625 SUCR1_HUMAN  600.71   7.604  49.345  78.472  53.756   88.611

                          c0007  c0008  c0009  c0010  ...     p1071     p1072  \
id chem      prot                                     ...
0  C01389645 BKRB2_HUMAN  0.559  0.978  0.623  1.133  ...  0.000559  0.000420
   C00281394 BKRB2_HUMAN  0.626  0.998  0.673  1.125  ...  0.000559  0.000420
5  C00995841 BKRB2_HUMAN  0.588  1.012  0.633  1.136  ...  0.000559  0.000420
0  C00072985 BKRB2_HUMAN  0.738  1.017  0.780  1.103  ...  0.000559  0.000420
5  C00353368 BKRB2_HUMAN  0.600  1.003  0.632  1.141  ...  0.000559  0.000420
...                         ...    ...    ...    ...  ...       ...       ...
   C00104971 NMUR2_HUMAN  0.590  0.983  0.641  1.128  ... -0.000795  0.000678
0  C01718162 CML1_HUMAN   0.561  0.991  0.608  1.133  ...  0.004885  0.004065
5  C00348566 CML1_HUMAN   0.686  1.009  0.717  1.109  ...  0.004885  0.004065
0  C00021215 SUCR1_HUMAN  0.603  1.069  0.579  1.149  ...  0.001155  0.002504
5  C00453625 SUCR1_HUMAN  0.625  0.993  0.680  1.122  ...  0.001155  0.002504

                             p1073     p1074     p1075     p1076     p1077  \
id chem      prot
0  C01389645 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
   C00281394 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
5  C00995841 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
0  C00072985 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
5  C00353368 BKRB2_HUMAN  0.001333  0.003081  0.004787  0.001735  0.004522
...                            ...       ...       ...       ...       ...
   C00104971 NMUR2_HUMAN  0.003468 -0.004946 -0.001317 -0.002964 -0.001042
0  C01718162 CML1_HUMAN   0.004887  0.001522  0.003042  0.003457  0.006119
5  C00348566 CML1_HUMAN   0.004887  0.001522  0.003042  0.003457  0.006119
0  C00021215 SUCR1_HUMAN  0.003405  0.002044  0.004069  0.001612  0.003456
5  C00453625 SUCR1_HUMAN  0.003405  0.002044  0.004069  0.001612  0.003456

                            p1078    p1079    p1080
id chem      prot
0  C01389645 BKRB2_HUMAN  190.160  149.947  156.745
   C00281394 BKRB2_HUMAN  190.160  149.947  156.745
5  C00995841 BKRB2_HUMAN  190.160  149.947  156.745
0  C00072985 BKRB2_HUMAN  190.160  149.947  156.745
5  C00353368 BKRB2_HUMAN  190.160  149.947  156.745
...                           ...      ...      ...
   C00104971 NMUR2_HUMAN  211.630  164.464  158.426
0  C01718162 CML1_HUMAN   191.358  146.038  149.270
5  C00348566 CML1_HUMAN   191.358  146.038  149.270
0  C00021215 SUCR1_HUMAN  168.568  140.875  138.337
5  C00453625 SUCR1_HUMAN  168.568  140.875  138.337

[248224 rows x 1974 columns]